
services:
  - type: web
    name: social-media-downloader-api
    env: python
    plan: starter
    buildCommand: |
      apt-get update && 
      apt-get install -y ffmpeg && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: "python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: MAX_WORKERS
        value: 1
    healthCheckPath: /health
